name: Deploy to S3 and CloudFront

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-southeast-1
  AWS_S3_BUCKET_NAME: yusiangeng
  DIR_TO_SYNC_WITH_S3: dist
  AWS_CLOUDFRONT_DISTRIBUTION_ID: E1HUGRG69EK5G3

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync files to S3 bucket
        run: |
          aws s3 sync ${{ env.DIR_TO_SYNC_WITH_S3 }} s3://${{ env.AWS_S3_BUCKET_NAME }} --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ env.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
